export const CREDIT_SAVE_REQUEST = "CREDIT_SAVE_REQUEST";
export const CREDIT_SAVE_SUCCESS = "CREDIT_SAVE_SUCCESS";
export const CREDIT_SAVE_FAIL = "CREDIT_SAVE_FAIL";

export const CREDIT_LIST_REQUEST = "CREDIT_LIST_REQUEST";
export const CREDIT_LIST_SUCCESS = "CREDIT_LIST_SUCCESS";
export const CREDIT_LIST_FAIL = "CREDIT_LIST_FAIL";

export const CREDIT_PAY_REQUEST = "CREDIT_PAY_REQUEST";
export const CREDIT_PAY_SUCCESS = "CREDIT_PAY_SUCCESS";
export const CREDIT_PAY_FAIL = "CREDIT_PAY_FAIL";