export const DEBIT_SAVE_REQUEST = "DEBIT_SAVE_REQUEST";
export const DEBIT_SAVE_SUCCESS = "DEBIT_SAVE_SUCCESS";
export const DEBIT_SAVE_FAIL = "DEBIT_SAVE_FAIL";

export const DEBITS_LIST_REQUEST = "DEBIT_LIST_REQUEST";
export const DEBITS_LIST_SUCCESS = "DEBIT_LIST_SUCCESS";
export const DEBITS_LIST_FAIL = "DEBIT_LIST_FAIL";

export const DEBIT_PAY_REQUEST = "DEBIT_PAY_REQUEST";
export const DEBIT_PAY_SUCCESS = "DEBIT_PAY_SUCCESS";
export const DEBIT_PAY_FAIL = "DEBIT_PAY_FAIL";