export const EXPENSE_REGISTER_REQUEST = "EXPENSE_REGISTER_REQUEST";
export const EXPENSE_SUCCESS_REQUEST = "EXPENSE_SUCCESS_REQUEST";
export const EXPENSE_FAIL_REQUEST = "EXPENSE_FAIL_REQUEST";

export const FECTCH_EXPENSES_REQUEST = "FECTCH_EXPENSES_REQUEST";
export const FECTCH_EXPENSES_SUCCESS = "FECTCH_EXPENSES_SUCCESS";
export const FECTCH_EXPENSES_FAIL= "FECTCH_EXPENSES_FAIL";




